export default [
    ['Action (set A)', 'Action (set B)', 'Action (set C)', 'Adjective', 'Animal (set A)', 'Animal (set B)', 'Fruits', 'Transport'],
    [{
            word: 'cry',
            translation: 'плакать',
            image: 'img/cry.jpg',
            audioSrc: 'audio/cry.mp3',
        },
        {
            word: 'dance',
            translation: 'танцевать',
            image: 'img/dance.jpg',
            audioSrc: 'audio/dance.mp3',
        },
        {
            word: 'dive',
            translation: 'нырять',
            image: 'img/dive.jpg',
            audioSrc: 'audio/dive.mp3',
        },
        {
            word: 'draw',
            translation: 'рисовать',
            image: 'img/draw.jpg',
            audioSrc: 'audio/draw.mp3',
        },
        {
            word: 'fish',
            translation: 'ловить рыбу',
            image: 'img/fish.jpg',
            audioSrc: 'audio/fish.mp3',
        },
        {
            word: 'fly',
            translation: 'летать',
            image: 'img/fly.jpg',
            audioSrc: 'audio/fly.mp3',
        },
        {
            word: 'hug',
            translation: 'обнимать',
            image: 'img/hug.jpg',
            audioSrc: 'audio/hug.mp3',
        },
        {
            word: 'jump',
            translation: 'прыгать',
            image: 'img/jump.jpg',
            audioSrc: 'audio/jump.mp3',
        },
    ],
    [{
            word: 'open',
            translation: 'открывать',
            image: 'img/open.jpg',
            audioSrc: 'audio/open.mp3',
        },
        {
            word: 'play',
            translation: 'играть',
            image: 'img/play.jpg',
            audioSrc: 'audio/play.mp3',
        },
        {
            word: 'point',
            translation: 'указывать',
            image: 'img/point.jpg',
            audioSrc: 'audio/point.mp3',
        },
        {
            word: 'ride',
            translation: 'ездить',
            image: 'img/ride.jpg',
            audioSrc: 'audio/ride.mp3',
        },
        {
            word: 'run',
            translation: 'бегать',
            image: 'img/run.jpg',
            audioSrc: 'audio/run.mp3',
        },
        {
            word: 'sing',
            translation: 'петь',
            image: 'img/sing.jpg',
            audioSrc: 'audio/sing.mp3',
        },
        {
            word: 'skip',
            translation: 'пропускать, прыгать',
            image: 'img/skip.jpg',
            audioSrc: 'audio/skip.mp3',
        },
        {
            word: 'swim',
            translation: 'плавать',
            image: 'img/swim.jpg',
            audioSrc: 'audio/swim.mp3',
        },
    ],
    [{
            word: 'argue',
            translation: 'спорить',
            image: 'img/argue.jpg',
            audioSrc: 'audio/argue.mp3',
        },
        {
            word: 'build',
            translation: 'строить',
            image: 'img/build.jpg',
            audioSrc: 'audio/build.mp3',
        },
        {
            word: 'carry',
            translation: 'нести',
            image: 'img/carry.jpg',
            audioSrc: 'audio/carry.mp3',
        },
        {
            word: 'catch',
            translation: 'ловить',
            image: 'img/catch.jpg',
            audioSrc: 'audio/catch.mp3',
        },
        {
            word: 'drive',
            translation: 'водить',
            image: 'img/drive.jpg',
            audioSrc: 'audio/drive.mp3',
        },
        {
            word: 'drop',
            translation: 'падать',
            image: 'img/drop.jpg',
            audioSrc: 'audio/drop.mp3',
        },
        {
            word: 'pull',
            translation: 'тянуть',
            image: 'img/pull.jpg',
            audioSrc: 'audio/pull.mp3',
        },
        {
            word: 'push',
            translation: 'толкать',
            image: 'img/push.jpg',
            audioSrc: 'audio/push.mp3',
        },
    ],
    [{
            word: 'big',
            translation: 'большой',
            image: 'img/big.jpg',
            audioSrc: 'audio/big.mp3',
        },
        {
            word: 'small',
            translation: 'маленький',
            image: 'img/small.jpg',
            audioSrc: 'audio/small.mp3',
        },
        {
            word: 'fast',
            translation: 'быстрый',
            image: 'img/fast.jpg',
            audioSrc: 'audio/fast.mp3',
        },
        {
            word: 'slow',
            translation: 'медленный',
            image: 'img/slow.jpg',
            audioSrc: 'audio/slow.mp3',
        },
        {
            word: 'friendly',
            translation: 'дружелюбный',
            image: 'img/friendly.jpg',
            audioSrc: 'audio/friendly.mp3',
        },
        {
            word: 'unfriendly',
            translation: 'недружелюбный',
            image: 'img/unfriendly.jpg',
            audioSrc: 'audio/unfriendly.mp3',
        },
        {
            word: 'young',
            translation: 'молодой',
            image: 'img/young.jpg',
            audioSrc: 'audio/young.mp3',
        },
        {
            word: 'old',
            translation: 'старый',
            image: 'img/old.jpg',
            audioSrc: 'audio/old.mp3',
        },
    ],
    [{
            word: 'cat',
            translation: 'кот',
            image: 'img/cat.jpg',
            audioSrc: 'audio/cat.mp3',
        },
        {
            word: 'chick',
            translation: 'цыплёнок',
            image: 'img/chick.jpg',
            audioSrc: 'audio/chick.mp3',
        },
        {
            word: 'chicken',
            translation: 'курица',
            image: 'img/chicken.jpg',
            audioSrc: 'audio/chicken.mp3',
        },
        {
            word: 'dog',
            translation: 'собака',
            image: 'img/dog.jpg',
            audioSrc: 'audio/dog.mp3',
        },
        {
            word: 'horse',
            translation: 'лошадь',
            image: 'img/horse.jpg',
            audioSrc: 'audio/horse.mp3',
        },
        {
            word: 'pig',
            translation: 'свинья',
            image: 'img/pig.jpg',
            audioSrc: 'audio/pig.mp3',
        },
        {
            word: 'rabbit',
            translation: 'кролик',
            image: 'img/rabbit.jpg',
            audioSrc: 'audio/rabbit.mp3',
        },
        {
            word: 'sheep',
            translation: 'овца',
            image: 'img/sheep.jpg',
            audioSrc: 'audio/sheep.mp3',
        },
    ],
    [{
            word: 'bird',
            translation: 'птица',
            image: 'img/bird.jpg',
            audioSrc: 'audio/bird.mp3',
        },
        {
            word: 'fish',
            translation: 'рыба',
            image: 'img/fish1.jpg',
            audioSrc: 'audio/fish.mp3',
        },
        {
            word: 'frog',
            translation: 'жаба',
            image: 'img/frog.jpg',
            audioSrc: 'audio/frog.mp3',
        },
        {
            word: 'giraffe',
            translation: 'жираф',
            image: 'img/giraffe.jpg',
            audioSrc: 'audio/giraffe.mp3',
        },
        {
            word: 'lion',
            translation: 'лев',
            image: 'img/lion.jpg',
            audioSrc: 'audio/lion.mp3',
        },
        {
            word: 'mouse',
            translation: 'мышь',
            image: 'img/mouse.jpg',
            audioSrc: 'audio/mouse.mp3',
        },
        {
            word: 'turtle',
            translation: 'черепаха',
            image: 'img/turtle.jpg',
            audioSrc: 'audio/turtle.mp3',
        },
        {
            word: 'dolphin',
            translation: 'дельфин',
            image: 'img/dolphin.jpg',
            audioSrc: 'audio/dolphin.mp3',
        },
    ],
    [{
            word: 'pineapple',
            translation: 'ананас',
            image: 'img/pineapple.jpg',
            audioSrc: 'audio/pineapple.mp3',
        },
        {
            word: 'pear',
            translation: 'груша',
            image: 'img/pear.jpg',
            audioSrc: 'audio/pear.mp3',
        },
        {
            word: 'peach',
            translation: 'персик',
            image: 'img/peach.jpg',
            audioSrc: 'audio/peach.mp3',
        },
        {
            word: 'orange',
            translation: 'апельсин',
            image: 'img/orange.jpg',
            audioSrc: 'audio/orange.mp3',
        },
        {
            word: 'lemon',
            translation: 'лимон',
            image: 'img/lemon.jpg',
            audioSrc: 'audio/lemon.mp3',
        },
        {
            word: 'banana',
            translation: 'банан',
            image: 'img/banana.jpg',
            audioSrc: 'audio/banana.mp3',
        },
        {
            word: 'avocado',
            translation: 'авокадо',
            image: 'img/avocado.jpg',
            audioSrc: 'audio/avocado.mp3',
        },
        {
            word: 'apple',
            translation: 'яблоко',
            image: 'img/apple.jpg',
            audioSrc: 'audio/apple.mp3',
        },
    ],
    [{
            word: 'airplane',
            translation: 'самолёт',
            image: 'img/airplane.jpg',
            audioSrc: 'audio/airplane.mp3',
        },
        {
            word: 'bus',
            translation: 'автобус',
            image: 'img/bus.jpg',
            audioSrc: 'audio/bus.mp3',
        },
        {
            word: 'car',
            translation: 'машина',
            image: 'img/car.jpg',
            audioSrc: 'audio/car.mp3',
        },
        {
            word: 'ship',
            translation: 'корабль',
            image: 'img/ship.jpg',
            audioSrc: 'audio/ship.mp3',
        },
        {
            word: 'train',
            translation: 'поезд',
            image: 'img/train.jpg',
            audioSrc: 'audio/train.mp3',
        },
        {
            word: 'bicycle',
            translation: 'велосипед',
            image: 'img/bicycle.jpg',
            audioSrc: 'audio/bicycle.mp3',
        },
        {
            word: 'helicopter',
            translation: 'вертолёт',
            image: 'img/helicopter.jpg',
            audioSrc: 'audio/helicopter.mp3',
        },
        {
            word: 'underground',
            translation: 'метро',
            image: 'img/underground.jpg',
            audioSrc: 'audio/underground.mp3',
        },
    ],
];